package com.srihari.vintix.effects

import kotlin.math.max

data class InstabilityBehavior(
    val exposureVariance: Float = 0f,
    val warmthVariance: Float = 0f,
    val noiseVariance: Float = 0f,
) {
    fun jitter(base: Float, variance: Float): Float {
        if (variance <= 0f) return base
        return base + (Math.random().toFloat() * 2f - 1f) * variance
    }
}

data class FeedbackBehavior(
    val useDigitalBeep: Boolean = false,
    val soundEnabled: Boolean = true,
    val hapticFeedback: Boolean = true,
    val captureFreezeMs: Long = 100L,
    val flashFadeDurationMs: Int = 160,
)

enum class AspectRatio(val ratio: Float, val label: String) {
    RATIO_4_3(4f / 3f, "4:3"),
    RATIO_3_2(3f / 2f, "3:2"),
    RATIO_16_9(16f / 9f, "16:9"),
}

data class CameraProfile(
    val displayName: String,
    val vibeLabel: String,
    val contrast: Float,
    val saturation: Float,
    val warmth: Float,
    val coolHighlights: Float,
    val magentaShift: Float,
    val cyanShift: Float,
    val exposure: Float,
    val shadowCrush: Float,
    val fadedBlacks: Float,
    val highlightClip: Float,
    val bloom: Float,
    val bloomThreshold: Float,
    val bloomSpread: Float,
    val bloomWarmth: Float,
    val sharpen: Float,
    val softness: Float,
    val grain: Float,
    val grainCoarseness: Float,
    val chromaNoise: Float,
    val jpegArtifacts: Float,
    val macroblockStrength: Float,
    val mosquitoNoise: Float,
    val chromaSmear: Float,
    val vignette: Float,
    val flashBurn: Float,
    val horizontalSmear: Float,
    val ccdStreak: Float,
    val scanlineStrength: Float,
    val haze: Float,
    val pastelLift: Float,
    val shadowBlue: Float,
    val shadowGreen: Float,
    val highlightRed: Float,
    val highlightGreen: Float,
    val highlightBlue: Float,
    val jpegQuality: Int,
    val aspectRatio: AspectRatio = AspectRatio.RATIO_4_3,
    val exportResolution: Int? = 1600,
    val instabilityBehavior: InstabilityBehavior = InstabilityBehavior(),
    val feedbackBehavior: FeedbackBehavior = FeedbackBehavior(),
) {
    fun applyInstability(): CameraProfile {
        val behavior = instabilityBehavior
        return copy(
            exposure = max(0f, behavior.jitter(exposure, behavior.exposureVariance)),
            warmth = behavior.jitter(warmth, behavior.warmthVariance),
            grain = max(0f, behavior.jitter(grain, behavior.noiseVariance)),
            chromaNoise = max(0f, behavior.jitter(chromaNoise, behavior.noiseVariance * 0.7f)),
        )
    }

    companion object {
        val Default = CameraProfiles.CyberShot2003
    }
}

object CameraProfiles {
    val CyberShot2003 = CameraProfile(
        displayName = "CYBERSHOT 2003",
        vibeLabel = "CCD POP",
        contrast = 1.24f,
        saturation = 1.06f,
        warmth = 0.10f,
        coolHighlights = 0.22f,
        magentaShift = 0.07f,
        cyanShift = 0.03f,
        exposure = 1.04f,
        shadowCrush = 0.34f,
        fadedBlacks = 0.02f,
        highlightClip = 0.48f,
        bloom = 0.58f,
        bloomThreshold = 0.68f,
        bloomSpread = 0.60f,
        bloomWarmth = 0.10f,
        sharpen = 0.48f,
        softness = 0.15f,
        grain = 0.26f,
        grainCoarseness = 0.18f,
        chromaNoise = 0.24f,
        jpegArtifacts = 0.45f,
        macroblockStrength = 0.3f,
        mosquitoNoise = 0.2f,
        chromaSmear = 0.15f,
        vignette = 0.10f,
        flashBurn = 0.35f,
        horizontalSmear = 0f,
        ccdStreak = 0.06f,
        scanlineStrength = 0f,
        haze = 0.0f,
        pastelLift = 0.02f,
        shadowBlue = 0.08f,
        shadowGreen = 0.00f,
        highlightRed = 0.03f,
        highlightGreen = 0.01f,
        highlightBlue = 0.08f,
        jpegQuality = 86,
        exportResolution = 2048,
        instabilityBehavior = InstabilityBehavior(0.04f, 0.05f, 0.05f),
        feedbackBehavior = FeedbackBehavior(useDigitalBeep = true, flashFadeDurationMs = 130),
    )

    val AngelDream = CameraProfile(
        displayName = "ANGEL DREAM",
        vibeLabel = "HEAVENLY",
        contrast = 0.92f,
        saturation = 0.94f,
        warmth = 0.10f,
        coolHighlights = 0.12f,
        magentaShift = 0.04f,
        cyanShift = 0.08f,
        exposure = 1.07f,
        shadowCrush = 0.05f,
        fadedBlacks = 0.13f,
        highlightClip = 0.30f,
        bloom = 0.72f,
        bloomThreshold = 0.75f,
        bloomSpread = 0.92f,
        bloomWarmth = 0.24f,
        sharpen = 0.10f,
        softness = 0.1f,
        grain = 0.12f,
        grainCoarseness = 0.08f,
        chromaNoise = 0.08f,
        jpegArtifacts = 0.08f,
        macroblockStrength = 0.00f,
        mosquitoNoise = 0.02f,
        chromaSmear = 0.04f,
        vignette = 0.04f,
        flashBurn = 0.08f,
        horizontalSmear = 0f,
        ccdStreak = 0.04f,
        scanlineStrength = 0f,
        haze = 0.05f,
        pastelLift = 0.20f,
        shadowBlue = 0.12f,
        shadowGreen = 0.04f,
        highlightRed = 0.08f,
        highlightGreen = 0.07f,
        highlightBlue = 0.04f,
        jpegQuality = 92,
        exportResolution = 2048,
        instabilityBehavior = InstabilityBehavior(0.03f, 0.04f, 0.02f),
        feedbackBehavior = FeedbackBehavior(useDigitalBeep = false, flashFadeDurationMs = 220),
    )

    val DisposableFilm = CameraProfile(
        displayName = "DISPOSABLE FILM",
        vibeLabel = "FLASH FADE",
        contrast = 0.85f,
        saturation = 0.84f,
        warmth = 0.36f,
        coolHighlights = 0.00f,
        magentaShift = 0.05f,
        cyanShift = -0.02f,
        exposure = 1.04f,
        shadowCrush = 0.4f,
        fadedBlacks = 0.20f,
        highlightClip = 0.38f,
        bloom = 0.32f,
        bloomThreshold = 0.66f,
        bloomSpread = 0.66f,
        bloomWarmth = 0.52f,
        sharpen = 0.12f,
        softness = 0.25f,
        grain = 0.65f,
        grainCoarseness = 0.45f,
        chromaNoise = 0.24f,
        jpegArtifacts = 0.22f,
        macroblockStrength = 0.08f,
        mosquitoNoise = 0.06f,
        chromaSmear = 0.10f,
        vignette = 0.4f,
        flashBurn = 0.48f,
        horizontalSmear = 0f,
        ccdStreak = 0f,
        scanlineStrength = 0f,
        haze = 0.08f,
        pastelLift = 0.06f,
        shadowBlue = -0.02f,
        shadowGreen = 0.00f,
        highlightRed = 0.12f,
        highlightGreen = 0.07f,
        highlightBlue = -0.02f,
        jpegQuality = 84,
        aspectRatio = AspectRatio.RATIO_3_2,
        exportResolution = 1600,
        instabilityBehavior = InstabilityBehavior(0.10f, 0.10f, 0.08f),
        feedbackBehavior = FeedbackBehavior(useDigitalBeep = false, flashFadeDurationMs = 220),
    )

    val Vga1999 = CameraProfile(
        displayName = "VGA 1999",
        vibeLabel = "640K GHOST",
        contrast = 1.10f,
        saturation = 0.72f,
        warmth = -0.04f,
        coolHighlights = 0.16f,
        magentaShift = 0.10f,
        cyanShift = 0.08f,
        exposure = 1.05f,
        shadowCrush = 0.30f,
        fadedBlacks = 0.08f,
        highlightClip = 0.56f,
        bloom = 0.22f,
        bloomThreshold = 0.72f,
        bloomSpread = 0.42f,
        bloomWarmth = -0.08f,
        sharpen = 0.85f,
        softness = 0.0f,
        grain = 0.76f,
        grainCoarseness = 0.54f,
        chromaNoise = 0.74f,
        jpegArtifacts = 0.90f,
        macroblockStrength = 0.75f,
        mosquitoNoise = 0.65f,
        chromaSmear = 0.6f,
        vignette = 0.08f,
        flashBurn = 0.08f,
        horizontalSmear = 0.08f,
        ccdStreak = 0.08f,
        scanlineStrength = 0f,
        haze = 0.02f,
        pastelLift = 0.00f,
        shadowBlue = 0.06f,
        shadowGreen = -0.02f,
        highlightRed = 0.01f,
        highlightGreen = 0.00f,
        highlightBlue = 0.06f,
        jpegQuality = 46,
        exportResolution = 640,
        instabilityBehavior = InstabilityBehavior(0.08f, 0.10f, 0.12f),
        feedbackBehavior = FeedbackBehavior(useDigitalBeep = true, flashFadeDurationMs = 170),
    )

    val NightCyber = CameraProfile(
        displayName = "NIGHT CYBER",
        vibeLabel = "RAIN NEON",
        contrast = 1.30f,
        saturation = 1.05f,
        warmth = -0.20f,
        coolHighlights = 0.38f,
        magentaShift = 0.18f,
        cyanShift = 0.18f,
        exposure = 0.95f,
        shadowCrush = 0.48f,
        fadedBlacks = 0.02f,
        highlightClip = 0.44f,
        bloom = 0.66f,
        bloomThreshold = 0.55f,
        bloomSpread = 0.78f,
        bloomWarmth = -0.36f,
        sharpen = 0.24f,
        softness = 0.02f,
        grain = 0.6f,
        grainCoarseness = 0.30f,
        chromaNoise = 0.65f,
        jpegArtifacts = 0.24f,
        macroblockStrength = 0.10f,
        mosquitoNoise = 0.18f,
        chromaSmear = 0.20f,
        vignette = 0.18f,
        flashBurn = 0.02f,
        horizontalSmear = 0.22f,
        ccdStreak = 0.7f,
        scanlineStrength = 0.02f,
        haze = 0.04f,
        pastelLift = 0.00f,
        shadowBlue = 0.16f,
        shadowGreen = 0.05f,
        highlightRed = 0.07f,
        highlightGreen = 0.03f,
        highlightBlue = 0.18f,
        jpegQuality = 84,
        exportResolution = 1800,
        instabilityBehavior = InstabilityBehavior(0.05f, 0.06f, 0.08f),
        feedbackBehavior = FeedbackBehavior(useDigitalBeep = true, flashFadeDurationMs = 150),
    )

    val HandycamMemory = CameraProfile(
        displayName = "HANDYCAM MEMORY",
        vibeLabel = "HOME TAPE",
        contrast = 0.8f,
        saturation = 0.65f,
        warmth = 0.35f,
        coolHighlights = 0.02f,
        magentaShift = 0.03f,
        cyanShift = 0.02f,
        exposure = 1.01f,
        shadowCrush = 0.10f,
        fadedBlacks = 0.12f,
        highlightClip = 0.24f,
        bloom = 0.24f,
        bloomThreshold = 0.68f,
        bloomSpread = 0.70f,
        bloomWarmth = 0.28f,
        sharpen = 0.04f,
        softness = 0.2f,
        grain = 0.26f,
        grainCoarseness = 0.22f,
        chromaNoise = 0.24f,
        jpegArtifacts = 0.18f,
        macroblockStrength = 0.04f,
        mosquitoNoise = 0.06f,
        chromaSmear = 0.20f,
        vignette = 0.04f,
        flashBurn = 0.00f,
        horizontalSmear = 0.45f,
        ccdStreak = 0.06f,
        scanlineStrength = 0.25f,
        haze = 0.10f,
        pastelLift = 0.04f,
        shadowBlue = 0.02f,
        shadowGreen = 0.00f,
        highlightRed = 0.09f,
        highlightGreen = 0.05f,
        highlightBlue = -0.02f,
        jpegQuality = 82,
        aspectRatio = AspectRatio.RATIO_16_9,
        exportResolution = 1280,
        instabilityBehavior = InstabilityBehavior(0.05f, 0.05f, 0.05f),
        feedbackBehavior = FeedbackBehavior(useDigitalBeep = true, flashFadeDurationMs = 90),
    )

    val GoldenHourCcd = CameraProfile(
        displayName = "GOLDEN HOUR CCD",
        vibeLabel = "SUN MEMORY",
        contrast = 1.06f,
        saturation = 1.02f,
        warmth = 0.55f,
        coolHighlights = -0.08f,
        magentaShift = 0.03f,
        cyanShift = -0.03f,
        exposure = 1.05f,
        shadowCrush = 0.10f,
        fadedBlacks = 0.25f,
        highlightClip = 0.6f,
        bloom = 0.65f,
        bloomThreshold = 0.60f,
        bloomSpread = 0.82f,
        bloomWarmth = 0.9f,
        sharpen = 0.12f,
        softness = 0.06f,
        grain = 0.22f,
        grainCoarseness = 0.18f,
        chromaNoise = 0.12f,
        jpegArtifacts = 0.10f,
        macroblockStrength = 0.02f,
        mosquitoNoise = 0.03f,
        chromaSmear = 0.05f,
        vignette = 0.10f,
        flashBurn = 0.06f,
        horizontalSmear = 0f,
        ccdStreak = 0.04f,
        scanlineStrength = 0f,
        haze = 0.12f,
        pastelLift = 0.08f,
        shadowBlue = -0.05f,
        shadowGreen = 0.02f,
        highlightRed = 0.18f,
        highlightGreen = 0.08f,
        highlightBlue = -0.05f,
        jpegQuality = 90,
        exportResolution = 2048,
        instabilityBehavior = InstabilityBehavior(0.05f, 0.08f, 0.03f),
        feedbackBehavior = FeedbackBehavior(useDigitalBeep = false, flashFadeDurationMs = 190),
    )

    val ColdWinterDigicam = CameraProfile(
        displayName = "COLD WINTER DIGICAM",
        vibeLabel = "SNOW CCD",
        contrast = 1.08f,
        saturation = 0.82f,
        warmth = -0.4f,
        coolHighlights = 0.5f,
        magentaShift = -0.01f,
        cyanShift = 0.14f,
        exposure = 1.04f,
        shadowCrush = 0.26f,
        fadedBlacks = 0.06f,
        highlightClip = 0.65f,
        bloom = 0.34f,
        bloomThreshold = 0.64f,
        bloomSpread = 0.62f,
        bloomWarmth = -0.48f,
        sharpen = 0.24f,
        softness = 0.02f,
        grain = 0.5f,
        grainCoarseness = 0.20f,
        chromaNoise = 0.45f,
        jpegArtifacts = 0.18f,
        macroblockStrength = 0.06f,
        mosquitoNoise = 0.10f,
        chromaSmear = 0.10f,
        vignette = 0.08f,
        flashBurn = 0.05f,
        horizontalSmear = 0f,
        ccdStreak = 0.08f,
        scanlineStrength = 0f,
        haze = 0.08f,
        pastelLift = 0.05f,
        shadowBlue = 0.3f,
        shadowGreen = 0.05f,
        highlightRed = -0.05f,
        highlightGreen = 0.02f,
        highlightBlue = 0.16f,
        jpegQuality = 88,
        exportResolution = 2048,
        instabilityBehavior = InstabilityBehavior(0.06f, 0.08f, 0.06f),
        feedbackBehavior = FeedbackBehavior(useDigitalBeep = true, flashFadeDurationMs = 130),
    )

    val Tumblr2012 = CameraProfile(
        displayName = "TUMBLR 2012",
        vibeLabel = "PASTEL WEB",
        contrast = 0.75f,
        saturation = 0.88f,
        warmth = 0.02f,
        coolHighlights = 0.10f,
        magentaShift = 0.10f,
        cyanShift = 0.08f,
        exposure = 1.06f,
        shadowCrush = 0.02f,
        fadedBlacks = 0.35f,
        highlightClip = 0.26f,
        bloom = 0.42f,
        bloomThreshold = 0.62f,
        bloomSpread = 0.74f,
        bloomWarmth = 0.08f,
        sharpen = 0.06f,
        softness = 0.06f,
        grain = 0.18f,
        grainCoarseness = 0.14f,
        chromaNoise = 0.10f,
        jpegArtifacts = 0.08f,
        macroblockStrength = 0.02f,
        mosquitoNoise = 0.03f,
        chromaSmear = 0.06f,
        vignette = 0.06f,
        flashBurn = 0.02f,
        horizontalSmear = 0f,
        ccdStreak = 0.02f,
        scanlineStrength = 0f,
        haze = 0.15f,
        pastelLift = 0.3f,
        shadowBlue = 0.09f,
        shadowGreen = 0.04f,
        highlightRed = 0.08f,
        highlightGreen = 0.05f,
        highlightBlue = 0.10f,
        jpegQuality = 92,
        exportResolution = 2048,
        instabilityBehavior = InstabilityBehavior(0.04f, 0.05f, 0.03f),
        feedbackBehavior = FeedbackBehavior(useDigitalBeep = false, flashFadeDurationMs = 170),
    )

    val RawMemory = CameraProfile(
        displayName = "RAW MEMORY",
        vibeLabel = "TRUE CCD",
        contrast = 1.02f,
        saturation = 0.95f,
        warmth = 0.08f,
        coolHighlights = 0.08f,
        magentaShift = 0.02f,
        cyanShift = 0.01f,
        exposure = 1.00f,
        shadowCrush = 0.14f,
        fadedBlacks = 0.05f,
        highlightClip = 0.24f,
        bloom = 0.1f,
        bloomThreshold = 0.70f,
        bloomSpread = 0.50f,
        bloomWarmth = 0.08f,
        sharpen = 0.16f,
        softness = 0.00f,
        grain = 0.08f,
        grainCoarseness = 0.10f,
        chromaNoise = 0.08f,
        jpegArtifacts = 0.08f,
        macroblockStrength = 0.02f,
        mosquitoNoise = 0.02f,
        chromaSmear = 0.02f,
        vignette = 0.03f,
        flashBurn = 0.02f,
        horizontalSmear = 0f,
        ccdStreak = 0.02f,
        scanlineStrength = 0f,
        haze = 0.03f,
        pastelLift = 0.01f,
        shadowBlue = 0.02f,
        shadowGreen = 0.00f,
        highlightRed = 0.02f,
        highlightGreen = 0.01f,
        highlightBlue = 0.02f,
        jpegQuality = 94,
        exportResolution = null,
        instabilityBehavior = InstabilityBehavior(0.02f, 0.03f, 0.02f),
        feedbackBehavior = FeedbackBehavior(useDigitalBeep = true, flashFadeDurationMs = 100),
    )

    val CyberShot = CyberShot2003
    val Disposable = DisposableFilm
    val Handycam = HandycamMemory

    val all: List<CameraProfile> = listOf(
        CyberShot2003,
        AngelDream,
        DisposableFilm,
        Vga1999,
        NightCyber,
        HandycamMemory,
        GoldenHourCcd,
        ColdWinterDigicam,
        Tumblr2012,
        RawMemory,
    )
}
